### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by James-Byrne** [ryal/ryal#5]
Hi Ben, read your blog post and really like the sound of the project. If theres anything I can help with let me know 😄

**Comment by BenMorganIO** [comment]
Hey @James-Byrne,

I've given you write access to the repo so that you can help out and I can attach you as a reviewer and assignee to issues/PRs.

Right now, I'm finishing up adding multiple payment methods. Considering your work, if you'd like to take a stab at some of that, that'd be amazing!

I've also got work on my end for doing a payment state machine. I'll be sure to add you and @marjaimate as reviewers when that PR comes in :)

**Comment by James-Byrne** [comment]
Hey @BenMorganIO,

Thats brilliant, I'm currently going through the code base and familiarising myself. Once I've got a better idea of the lay of the land I'll start on adding some other payment methods. 

If you think of anything in particular you want me to have a crack at just let me know :)
